services:
  postgres:
    image: postgres:15
    container_name: into-the-wild-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: into_the_wild
    ports:
      - "54325:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # OpenTripPlanner for carpooling route planning (disabled - needs proper OSM data setup)
  # opentripplanner:
  #   image: opentripplanner/opentripplanner:2.5.0
  #   container_name: into-the-wild-otp
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./otp/standalone:/var/opentripplanner
  #     - ./otp/cache:/var/otp/cache
  #   environment:
  #     - JAVA_TOOL_OPTIONS=-Xmx8G
  #   command: --build --serve /var/opentripplanner

  # Simple backend for OTP API integration
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: into-the-wild-backend
    restart: always
    ports:
      - "3003:3001"
    environment:
      - PORT=3001
      - OTP_URL=http://localhost:8080  # Fallback URL (OTP not running)

volumes:
  pgdata: {}
