version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: into-the-wild-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: into_the_wild
    ports:
      - "54322:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
